#!/usr/bin/env bash
# Generate the SQL embedded in the release binary from the canonical changelog.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT="${REPO_ROOT}/internal/db/schema/init.sql"
TMP="$(mktemp)"
trap 'rm -f "${TMP}"' EXIT

{
  echo "-- Code generated by scripts/db/generate-init-sql.sh; DO NOT EDIT."
  echo "-- Source: internal/db/schema/changelog/*.sql"
  cat "${REPO_ROOT}"/internal/db/schema/changelog/*.sql
} > "${TMP}"

if [[ "${1:-}" == "--check" ]]; then
  if ! cmp -s "${TMP}" "${OUTPUT}"; then
    echo "${OUTPUT} is stale; run scripts/db/generate-init-sql.sh" >&2
    exit 1
  fi
  exit 0
fi

install -m 0644 "${TMP}" "${OUTPUT}"
