-- Code generated by scripts/db/generate-init-sql.sh; DO NOT EDIT.
-- Source: internal/db/schema/changelog/*.sql
-- Momentum SQLite schema changelog, version 1.
--
-- This is the sole authoritative definition of a fresh Momentum database.
-- scripts/db/generate-init-sql.sh derives ../init.sql from this file; the Go
-- binary embeds that generated artifact for first-run startup.
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS backends (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    backend_type TEXT NOT NULL,
    name TEXT NOT NULL,
    config_encrypted TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    backend_id INTEGER NOT NULL,
    external_id TEXT,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL,
    priority INTEGER,
    due_at TIMESTAMP,
    tags_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (backend_id) REFERENCES backends(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_backends_user_id ON backends(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_backend_id ON tasks(backend_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_due_at ON tasks(due_at);

-- The local backend is the out-of-box task store used by the unauthenticated
-- Phase 1 server. It also makes the fresh release-binary task API usable.
INSERT OR IGNORE INTO users (id, email) VALUES (1, 'local@momentum.invalid');
INSERT OR IGNORE INTO backends (id, user_id, backend_type, name)
VALUES (1, 1, 'internal', 'Local tasks');
-- Momentum authentication schema, version 2.
CREATE TABLE IF NOT EXISTS credentials (
    user_id INTEGER NOT NULL,
    type TEXT NOT NULL,
    secret_hash TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, type),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_credentials_user_id ON credentials(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);
