-- Code generated by scripts/db/generate-init-sql.sh; DO NOT EDIT.
-- Source: internal/db/schema/changelog/*.sql
-- Momentum SQLite schema changelog, version 1.
--
-- This is the sole authoritative definition of a fresh Momentum database.
-- scripts/db/generate-init-sql.sh derives ../init.sql from this file; the Go
-- binary embeds that generated artifact for first-run startup.
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS backends (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    backend_type TEXT NOT NULL,
    name TEXT NOT NULL,
    config_encrypted TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    backend_id INTEGER NOT NULL,
    external_id TEXT,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL,
    priority INTEGER,
    due_at TIMESTAMP,
    uid TEXT,
    start_at TIMESTAMP,
    completed_at TIMESTAMP,
    dtstamp TIMESTAMP,
    last_modified TIMESTAMP,
    sequence INTEGER NOT NULL DEFAULT 0,
    percent_complete INTEGER,
    tags_json TEXT,
    related_to_json TEXT,
    url TEXT,
    location TEXT,
    extra_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (backend_id) REFERENCES backends(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_backends_user_id ON backends(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_backend_id ON tasks(backend_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_due_at ON tasks(due_at);

-- The local backend is the out-of-box task store used by the unauthenticated
-- Phase 1 server. It also makes the fresh release-binary task API usable.
INSERT OR IGNORE INTO users (id, email) VALUES (1, 'local@momentum.invalid');
INSERT OR IGNORE INTO backends (id, user_id, backend_type, name)
VALUES (1, 1, 'internal', 'Local tasks');
-- Momentum authentication schema, version 2.
CREATE TABLE IF NOT EXISTS credentials (
    user_id INTEGER NOT NULL,
    type TEXT NOT NULL,
    secret_hash TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, type),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_credentials_user_id ON credentials(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);
-- Canonical VTODO persistence fields, schema version 3.
CREATE UNIQUE INDEX IF NOT EXISTS idx_tasks_uid ON tasks(uid) WHERE uid IS NOT NULL;
-- Canonical synchronization state, schema version 4.
-- All provider-specific state is keyed by the owning backend and is retained
-- so a failed sync can be resumed and diagnosed without guessing.
CREATE TABLE IF NOT EXISTS sync_checkpoints (
    backend_id INTEGER PRIMARY KEY,
    cursor TEXT,
    status TEXT NOT NULL DEFAULT 'idle',
    last_started_at TIMESTAMP,
    last_completed_at TIMESTAMP,
    last_error TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (backend_id) REFERENCES backends(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sync_entities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    backend_id INTEGER NOT NULL,
    task_id INTEGER,
    remote_uid TEXT NOT NULL,
    remote_href TEXT,
    remote_etag TEXT,
    remote_sequence INTEGER,
    state TEXT NOT NULL DEFAULT 'active',
    last_pulled_at TIMESTAMP,
    last_pushed_at TIMESTAMP,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (backend_id) REFERENCES backends(id) ON DELETE CASCADE,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sync_entities_backend_uid ON sync_entities(backend_id, remote_uid);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sync_entities_backend_task ON sync_entities(backend_id, task_id) WHERE task_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_sync_entities_backend_state ON sync_entities(backend_id, state);

CREATE TABLE IF NOT EXISTS sync_operations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    backend_id INTEGER NOT NULL,
    entity_id INTEGER,
    direction TEXT NOT NULL,
    operation TEXT NOT NULL,
    outcome TEXT NOT NULL,
    error TEXT,
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    FOREIGN KEY (backend_id) REFERENCES backends(id) ON DELETE CASCADE,
    FOREIGN KEY (entity_id) REFERENCES sync_entities(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_sync_operations_retry ON sync_operations(backend_id, outcome, next_attempt_at);

CREATE TABLE IF NOT EXISTS sync_conflicts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    backend_id INTEGER NOT NULL,
    entity_id INTEGER,
    task_id INTEGER,
    local_snapshot TEXT NOT NULL,
    remote_snapshot TEXT NOT NULL,
    policy TEXT NOT NULL DEFAULT 'manual',
    status TEXT NOT NULL DEFAULT 'open',
    resolution TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    FOREIGN KEY (backend_id) REFERENCES backends(id) ON DELETE CASCADE,
    FOREIGN KEY (entity_id) REFERENCES sync_entities(id) ON DELETE SET NULL,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_sync_conflicts_backend_status ON sync_conflicts(backend_id, status);
